src/sk/ibm/sa/dao/UserController.java
package sk.ibm.sa.dao;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import sk.ibm.sa.Country;
import sk.ibm.sa.User;
import sk.ibm.sa.utils.LoginUtils;

public class UserController {
	
	private UserDao userDao;
	
	public UserController() {
		userDao = UserDaoFactory.getInstance().getUserDao();
	}

	public void addUser(User user) {
		userDao.addUser(user);	
	}

	public List<User> getAllUsers() {
		return userDao.getAllUsers();
	}
	
	public List<User> getAllUsersSortedByCountry() {
		 List<User> allUsers = userDao.getAllUsers();
		 Collections.sort(allUsers, new Comparator<User>() {
			@Override
			public int compare(User o1, User o2) {
				return o1.getAddress().getCountry().toString().compareTo(o2.getAddress().getCountry().toString());
			}
		});
		 return allUsers;
	}
	
	public List<User> getAllUsersSortedByName() {
		 List<User> allUsers = userDao.getAllUsers();
		 Collections.sort(allUsers);
		 return allUsers;
	}
	
	public List<User> getAllUsersSortedByEmailLength() {
		 List<User> allUsers = userDao.getAllUsers();
		 Collections.sort(allUsers, (User u1, User u2) -> u1.getEmail().length() - u2.getEmail().length());
		 return allUsers;
	}
	
	public List<User> getSlovakUsers() {
		 return userDao.getAllUsers().stream().filter(p -> p.getAddress().getCountry() 
				 == Country.SLOVAKIA).collect(Collectors.toList());
	}
	
	public double getAverageEmailLength() {
		return userDao.getAllUsers().stream().mapToInt(p -> p.getEmail().length()).average().getAsDouble();
	}
	
	public long getDistinctNameCount() {
		// musime pouzit map aby sme pracovali s menami nie pouzivatelmi
		return userDao.getAllUsers().stream().map(p -> p.getName()).distinct().count();
	}
	
	public long getUserCount() {
		return userDao.getUserCount();
	}
	
	/**
	 * 
	 * @param email
	 * @param password - unhashed
	 * @return
	 */
	public boolean hasUser(String email, String password) {
		String passHash = LoginUtils.hash(password);
		return userDao.hasUser(email, passHash);
	}
	
	
	
}

src/sk/ibm/sa/jsf/LoginServiceBean.java
package sk.ibm.sa.jsf;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

import sk.ibm.sa.Country;
import sk.ibm.sa.dao.UserController;
import sk.ibm.sa.utils.LoginUtils;
import sk.ibm.sa.utils.SessionUtils;

@Named("login")
@SessionScoped
public class LoginServiceBean implements Serializable{

	private UserController userController;
	
	private String email;
	/**
	 * password - unhashed
	 */
	private String password;
	
	private boolean isUserLogged;
	
	public LoginServiceBean() {
		userController = new UserController();
		isUserLogged = false;
	}
	
	public Country[] getCountries() {
		return Country.values();
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public boolean isUserLogged() {
		return isUserLogged;
	}

	public String login() {

		boolean valid = userController.hasUser(email, password);
		if (valid) {
			HttpSession httpSession = SessionUtils.getSession();
			httpSession.setAttribute("email", email);
			return "dashboard";
		} else {
			return "index";
		}
	}
	
	public String logout(){
		HttpSession session = SessionUtils.getSession();
		session.invalidate();
		return "index";
	}
}

src/sk/ibm/sa/jsf/RegistrationBean.java
package sk.ibm.sa.jsf;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import sk.ibm.sa.User;
import sk.ibm.sa.dao.UserController;

@Named("reg")
@RequestScoped
public class RegistrationBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private UserController userController = new UserController();
	
	private User user;
	
	public RegistrationBean() {
	
	}
	
	@PostConstruct
	public void init() {
		user = new User();
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	public void register() {
		userController.addUser(user);
	}
	
	

}

WebContent/dashboard.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<h:body> 
<h:form>
		<p>Welcome #{login.email}</p>
		<h:commandLink action="#{login.logout()}" value="Logout"></h:commandLink>
</h:form>
</h:body> 
</html>

WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Kupuj a predavaj</title>
	<h:outputStylesheet library="css" name="style.css"/>
</h:head>
<h:body>
	
	<h1>Vita vas Kupuj a predavaj.</h1>

	<ui:include src="/login.xhtml" />
	
	<ui:include src="/registration.xhtml" />
		
</h:body>
</html>

WebContent/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

	<h3>Login</h3>

	<h:form>
		<h:panelGrid columns="2" cellpadding="5" cellspacing="5" border="1">
			<h:outputLabel id="emailLabel" for="emailLogin" styleClass="text-input">Email:</h:outputLabel>
			<h:inputText id="emailLogin" value="#{login.email}" required="true" requiredMessage="*"></h:inputText>

			<h:outputLabel for="passLogin">Password:</h:outputLabel>
			<h:inputSecret id="passLogin" value="#{login.password}"></h:inputSecret>
			<f:facet name="footer">
				<h:panelGroup style="display:block; text-align:center">
					<h:commandButton id="submit" value="Login" action="#{login.login}"></h:commandButton>
				</h:panelGroup>
			</f:facet>
		</h:panelGrid>
	</h:form>

</ui:composition>

WebContent/registration.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

	<h3>Registration</h3>

	<h:form>
		<h:panelGrid columns="2" cellpadding="5" cellspacing="5" border="1">

			<h:outputLabel for="name">Name:</h:outputLabel>
			<h:inputText id="name" value="#{reg.user.name}"></h:inputText>

			<h:outputLabel for="surname">Surname:</h:outputLabel>
			<h:inputText id="surname" value="#{reg.user.surname}"></h:inputText>

			<h:outputLabel for="street">Street:</h:outputLabel>
			<h:inputText id="street" value="#{reg.user.address.street}"></h:inputText>

			<h:outputLabel for="postalCode">Postal Code:</h:outputLabel>
			<h:inputText id="postalCode" value="#{reg.user.address.postalCode}"></h:inputText>

			<h:outputLabel for="city">City:</h:outputLabel>
			<h:inputText id="city" value="#{reg.user.address.city}"></h:inputText>

			<h:outputLabel for="country">Country:</h:outputLabel>
			<h:selectOneMenu value="#{reg.user.address.country}">
				<f:selectItems value="#{login.countries}"/>
			</h:selectOneMenu>

			<h:outputLabel id="emailLabel" for="email">Email:</h:outputLabel>
			<h:inputText id="email" value="#{reg.user.email}"></h:inputText>

			<h:outputLabel for="pass">Password:</h:outputLabel>
			<h:inputSecret id="pass" value="#{reg.user.password}">
				<f:validateLength minimum="8"></f:validateLength>
			</h:inputSecret>
			<f:facet name="footer">
				<h:panelGroup style="display:block; text-align:center">
					<h:commandButton id="submit" value="Submit" action="#{reg.register}" />
				</h:panelGroup>
			</f:facet>
		</h:panelGrid>
	</h:form>

</ui:composition>

WebContent/users.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<h:body> 
<h3>welcome #{login.email}</h3>
<h:button outcome="#{login.logout()}" value="Logout"/>
</h:body> 
</html>